/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mintSol from "./mint.sol";
export type { mintSol };
import type * as nftSol from "./nft.sol";
export type { nftSol };
